**2.3类型**

In [7]:
# 检查类型
type(100)


int

In [6]:
type(100.1)

float

**2.4print语句**

In [9]:
x = 1/3
print(x)
y = 2/3
print(y)

0.3333333333333333
0.6666666666666666


In [11]:
print('x = ' + str(x))

x = 0.3333333333333333


In [14]:
# format 将字符串中的{  }部分替换为x的内容
print('weight = {} kg'.format(x))

weight = 0.3333333333333333 kg


In [16]:
x  = 1/3
y = 1/7
z = 1/4
print('weight = {0}kg, {1}kg, {2}kg'.format(x,y,z))
print('weight = {0:.2f}kg, {1:.2f}kg, {2:.2f}kg'.format(x,y,z))

weight = 0.3333333333333333kg, 0.14285714285714285kg, 0.25kg
weight = 0.33kg, 0.14kg, 0.25kg


**2.5list(数组变量)**

In [18]:
x  = [1,1,2,3,5] #list 的定义
print(x)

[1, 1, 2, 3, 5]


In [19]:
x[0]

1

In [21]:
print(type(x))
print(type(x[1]))

<class 'list'>
<class 'int'>


In [23]:
x[3] =100
print(x)

[1, 1, 2, 100, 5]


In [24]:
len(x)

5

*二维数组*

In [26]:
a = [[1,2,3],[4,5,6]]
print(a)

[[1, 2, 3], [4, 5, 6]]


In [27]:
print(a[0][1])

2


In [28]:
# 创建连续的整数数组
y = range(5,10)
print(y[0],y[1],y[2],y[3],y[4])

5 6 7 8 9


In [29]:
print(y)

range(5, 10)


In [30]:
z = list(range(5,10))
print(z)

[5, 6, 7, 8, 9]


In [31]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

**tuple(数组)**

In [32]:
a = (1,2,3)

In [33]:
print(a)

(1, 2, 3)


In [34]:
# 当函数中有多个返回值时，如果用一个变量接收，那么函数就会自动将该变量的类型设置为tuple类型

In [35]:
#长度为1的tuple
a = (1,)
print(type(a))

<class 'tuple'>


**2.7if语句**

In [5]:
x = 1
if x > 10:
    print('x is ')
    print('    larger than 10.')
else:
    print('x is smaller than 11')

x is smaller than 11


In [6]:
x >10

False

In [7]:
type(x > 10)

bool

**for 语句**

In [8]:
for i in [1,2,3]:
    print(i)

1
2
3


In [10]:
num = [2,4,6,8,10]
for i in range(len(num)):
    num[i] = num[i] * 2
print(num)

[4, 8, 12, 16, 20]


In [11]:
for i,n in enumerate(num):
    num[i] = n * 2
print(num)

[8, 16, 24, 32, 40]


**2.9向量**

In [1]:
import numpy as np

In [20]:
x = np.array([1,2])
x
print(x)

[1 2]


In [21]:
x = np.array([1,2])
y = np.array([2,4])
print(x+y)

[2 4]


In [22]:
type(x)

numpy.ndarray

In [23]:
print(x[0])

1


In [24]:
x[0] = 100
print(x)

[100   2]


In [26]:
#创建连续整数的向量
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [27]:
#注意复制ndarray类型的内容时不能用b=a,必须用b=a.copy()
a = np.array([1,1])
b = a
print('a=' + str(a))
print('b=' + str(b))
b[0] = 100
print('b = ' + str(b))
print('a = ' + str(a))

a=[1 1]
b=[1 1]
b = [100   1]
a = [100   1]


In [28]:
a = np.array([1,1])
b = a.copy()
print('a=' + str(a))
print('b=' + str(b))
b[0] = 100
print('b = ' + str(b))
print('a = ' + str(a))

a=[1 1]
b=[1 1]
b = [100   1]
a = [1 1]


In [29]:
#list 类型，可以先写 import copy 再令 a = copy.deepcopy(b)

**2.10矩阵**

In [3]:
x = np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [4]:
x.shape

(2, 3)

In [5]:
h,w = x.shape
print(h)
print(w)


2
3


In [6]:
x[1,2]

6

In [7]:
x[1,2]=100
print(x)

[[  1   2   3]
 [  4   5 100]]


*生成元素为0和1的ndarray*


In [8]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
x = np.zeros((2,10)) 
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [10]:
# size 是tuple类型
x = np.ones((2,10))
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [11]:
# 生成元素随机的矩阵
np.random.rand(2,3) #均匀分布在0-1 的随机数

array([[0.63883796, 0.08646742, 0.34810679],
       [0.64850969, 0.00352952, 0.32499922]])

In [12]:
np.random.randn(1,2)  #生成由服从均值0、方差1 的高斯分布的随机数构成的矩阵

array([[0.79732943, 0.97192495]])

In [13]:
np.random.randint(2,6,(2,2)) #生成由 low 到 high - 1 的随机整数构成的大小的size 矩阵

array([[5, 4],
       [4, 4]])

In [15]:
a  = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
a = a.reshape(2,5)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


**矩阵的四则运算**

In [17]:
x = np.array([[4,4,4],[8,8,8]])
y = np.array([[1,1,1],[2,2,2]])
print(x+y)

[[ 5  5  5]
 [10 10 10]]


In [18]:
print(10*x)

[[40 40 40]
 [80 80 80]]


In [19]:
print(np.sqrt(x))

[[2.         2.         2.        ]
 [2.82842712 2.82842712 2.82842712]]


In [20]:
v = np.array([[1,2,3],[4,5,6]])
w = np.array([[1,1],[2,2],[3,3]])
print(v.dot(w))

[[14 14]
 [32 32]]


**切片**

In [21]:
#  变量名[:n] 可以一次性读取从0 到 n-1 的元素

In [22]:
x = np.arange(10)
print(x)
print(x[:5])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [24]:
print(x[5:])

[5 6 7 8 9]


In [26]:
print(x[3:8])

[3 4 5 6 7]


In [28]:
print(x[3:8:2])

[3 5 7]


In [29]:
print(x[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [31]:
y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(y)
print(y[:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2]
 [5]]


**2.13 替换满足条件的数据**

In [3]:
x = np.array([1,1,2,3,5,8,13])
x>3

array([False, False, False, False,  True,  True,  True])

In [2]:
import numpy as np

In [4]:
x[x>3]

array([ 5,  8, 13])

In [6]:
x[x>3] = 999
print(x)

[  1   1   2   3 999 999 999]


**help用法**

In [7]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distributi

**函数**

In [10]:
def my_funcl():
    print('Hi!')
my_funcl()

Hi!


In [12]:
def my_func2(a,b):
    c = a+b
    return c
my_func2(1,2)

3

In [16]:
def my_func3(D):
    m = np.mean(D)
    s = np.std(D)
    return m,s

In [18]:
data = np.random.randn(100)
data_mean,data_std = my_func3(data)
print('mean:{0:.2f},std:{1:.2f}'.format(data_mean,data_std))

mean:0.02,std:0.89


**2.16 保存文件**

In [19]:
data = np.array([1,1,2,3,5,8,13])
print(data)

np.save('datafile.npy',data)
data = []
print(data)

data = np.load('datafile.npy')
print(data)

[ 1  1  2  3  5  8 13]
[]
[ 1  1  2  3  5  8 13]


In [20]:
data1 = np.array([1,2,3])
data2 = np.array([10,20,30])
np.savez('datafile2.npz',data1 = data1,data2=data2)
data1 = []
data2 = []
outfile = np.load('datafile2.npz')
print(outfile.files)
data1 = outfile['data1'] #查看存储变量的列表
data2 = outfile['data2']
print(data1)
print(data2)



['data1', 'data2']
[1 2 3]
[10 20 30]
